-- Baseline schema: the users / profiles tables that Hibernate previously created
-- via ddl-auto. Column types mirror Hibernate's generated DDL so that
-- ddl-auto=validate passes against these migrations.

create table users (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);

create table profiles (
    id bigint generated by default as identity,
    user_id bigint not null unique,
    name varchar(255) not null,
    cohort varchar(255),
    primary key (id),
    constraint fk_profiles_user foreign key (user_id) references users
);

create table profile_focus_areas (
    profile_id bigint not null,
    focus_area varchar(255),
    constraint fk_profile_focus_areas_profile foreign key (profile_id) references profiles
);
