-- Goal: a user-owned learning goal. Column types mirror Hibernate's generated
-- DDL so ddl-auto=validate passes against this migration.

create table goals (
    id bigint generated by default as identity,
    user_id bigint not null,
    title varchar(255) not null,
    description varchar(2000),
    status varchar(255) not null check (status in ('PLANNED', 'IN_PROGRESS', 'DONE')),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_goals_user foreign key (user_id) references users
);
