-- LearningSession: a study session logged against a Goal, plus its tags.
-- Column types mirror Hibernate's generated DDL so ddl-auto=validate passes.

create table learning_sessions (
    id bigint generated by default as identity,
    goal_id bigint not null,
    date date not null,
    duration_minutes integer not null,
    notes varchar(2000),
    primary key (id),
    constraint fk_learning_sessions_goal foreign key (goal_id) references goals
);

create table session_tags (
    session_id bigint not null,
    tag varchar(255),
    constraint fk_session_tags_session foreign key (session_id) references learning_sessions
);
